---
settings:
  name: Azure NetApp Files
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Azure NetApp Files Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Erste Schritte
    entries:
    - title: Informationen zu Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Workflow „Erste Schritte“
      url: "/task-quick-start.html"
    - title: Einrichten einer Microsoft Entra-Anwendung
      url: "/task-set-up-azure-ad.html"
    - title: Erstellen Sie ein System
      url: "/task-create-system.html"
  - title: Verwenden von Azure NetApp Files
    entries:
    - title: Erstellen und Mounten von Volumes
      url: "/task-create-volumes.html"
    - title: Vorhandene Volumes verwalten
      url: "/task-manage-volumes.html"
    - title: Entfernen von Azure NetApp Files
      url: "/task-remove-system.html"
  - title: Wissen und Unterstützung
    entries:
    - title: Für Support registrieren
      url: "/task-support-registration.html"
    - title: Hilfe erhalten
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
